### ISSUE TITLE
Wire the electronics

### ISSUE THREAD

**Issue by byllgrim** [Ifi-makers/trall-e#8]
The batteries, motors, controllers, etc must be connected.

**Comment by byllgrim** [comment]
Noe slikt:
https://drive.google.com/file/d/0B1_B_habMDm9WElta3V3VS1fTGs/view

**Comment by DinoDavid** [comment]
![image](https://user-images.githubusercontent.com/16984702/76364728-e9763780-6325-11ea-969d-3a44ad68b2d6.png)
